### ISSUE TITLE
readme error

### ISSUE THREAD

**Issue by ruoqianfengshao** [prncc/antd-scss-theme-plugin#29]
![image](https://user-images.githubusercontent.com/2928664/39033142-380a0dca-44a3-11e8-8c26-e561b79b117f.png)
Maybe it should be `AntdScssThemePlugin.themify('less-loader')` not `AntdScssThemePlugin('less-loader')` 😄

**Comment by prncc** [comment]
Thanks @ruoqianfengshao! You're correct and that's fixed now.
