### ISSUE TITLE
Parcel

### ISSUE THREAD

**Issue by reflog** [prncc/antd-scss-theme-plugin#30]
Amazing project! Is there any chance (long shot, I know) that you might look at implementing this plugin for Parcel bundler as well?

Thanks in advance!

**Comment by prncc** [comment]
Heya @reflog, thanks! I don't think I will be supporting Parcel in this project. From browsing Parcel's API docs I am tentatively optimistic that the utilities from this projects could be reused to make a Parcel plugin. If you'd like to go through with it, please feel free (`antd-scss-theme-plugin` is BSD-2 licensed). I would be happy to point you around the code here if you need me to.

**Comment by reflog** [comment]
Ok, thanks anyways!

**Comment by AbhimanyuG** [comment]
@reflog So did you create parcel plugin for this? If so, please share. Thanks!

**Comment by reflog** [comment]
@AbhimanyuG - no sorry, never got to it :)
