### ISSUE TITLE
scss compile error

### ISSUE THREAD

**Issue by izvonar** [prncc/antd-scss-theme-plugin#31]
If you use antd variable in *theme.scss* file without specifying it first, compilation fails with scss error.

theme.scss file

`
$input-border-color:$primary-color;
`

Fails because `$primary-color` is not defined.

I tried it in your example and got the same error.

**Comment by prncc** [comment]
Hey @izvonar, thanks for reporting. The plugin treats `theme.scss` as a regular SCSS file, so using theme variables without importing anything won't work. What you could do is create a file with the default variables (perhaps by modifying [the extractLessVariables method in utils.js](https://github.com/prncc/antd-scss-theme-plugin/blob/48beb1da5ec9a7c4e9205424b4ddea1089fbd9a3/src/utils.js#L16) and then import that, or use a second theme file which imports `theme.scss`.
