### ISSUE TITLE
$icon-url block compile

### ISSUE THREAD

**Issue by ruoqianfengshao** [prncc/antd-scss-theme-plugin#32]
I set `$icon-url` in `theme.scss` and it make webpack compile error

![image](https://user-images.githubusercontent.com/2928664/40531482-2408bb4e-602f-11e8-8549-b32feea87d43.png)

compile success without this variable.

Does this variable support to less?

**Comment by ruoqianfengshao** [comment]
I find varibale recognized by `scss-to-json`, `scss-to-json` will remove '//' and what's behind it.

**Comment by prncc** [comment]
@ruoqianfengshao Did you actually solve this issue, or have you given up trying to? If it's the latter, I'll reopen and see what can be done to fix it.

**Comment by ruoqianfengshao** [comment]
yeah, I fork [scss-to-json](https://github.com/ruoqianfengshao/scss-to-json) and [antd-scss-theme-plugin](https://github.com/ruoqianfengshao/antd-scss-theme-plugin), and solve this problem with not elegant way :).

**Comment by prncc** [comment]
@ruoqianfengshao I took a closer look. You should be able to fix your problem by escaping the slashes in the URL:

```
$icon-url: "https:\/\/at.alicdn.com\/t\/font_148784_v4ggb6wrjmkotj4i";
```
