### ISSUE TITLE
Module build failed: Error: Cannot find module 'sass-loader/lib/importsToResolve'

### ISSUE THREAD

**Issue by Gong-Elory** [prncc/antd-scss-theme-plugin#34]
in my node_modules, i can not find the dic  /lib/importsToResolve'

**Comment by Gong-Elory** [comment]
i get it haha~~

**Comment by sainisagar310** [comment]
Could you please share the snippet, how you have resolved this?

**Comment by sainisagar310** [comment]
It is not compatible with  `"sass-loader": "^7.2.0"`. Currently, I have fixed by changing the following in the module file `addSassLoader.js`.

`var _importsToResolve = require('sass-loader/dist/importsToResolve');`
to
`var _importsToResolve = require('sass-loader/lib/importsToResolve');`

**Comment by sainisagar310** [comment]
The other solution is, we can update the `sass-loader` to `7.3.1`.

**Comment by Abdilar** [comment]
It's so bad issue.
